name: Primer pipeline
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
jobs:
    build:
      runs-on: ubuntu-lastest

      steps:
      - uses: actions/checkout@v1
        name: Analisis del proyecto
      - name: Ejecución de un comando
        run: echo Está  ejecutando el pipeline
      - name: Ejecución de varios comandos
        run:
          echo Varias lineas
          ls -la
